<a href="https://colab.research.google.com/github/Hana-ElGabry/CareerPilot/blob/main/New_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import duckdb
import os
import glob
import time
from pathlib import Path

In [4]:
individuals_path ='/content/drive/MyDrive/NetMob25/data/data/individuals_dataset.csv'
Trips_path ='/content/drive/MyDrive/NetMob25/data/data/trips_dataset.csv'

In [5]:
ind_df = pd.read_csv(individuals_path)
trips_df = pd.read_csv(Trips_path)

In [6]:
ind_df.head(1)

,ID,CODGEO,AREA_NAME,SEX,AGE,DIPLOMA,PRO_CAT,TYPE_HOUSE,NBPERS_HOUSE,NB_10,...,TWO_WHEELER,BIKE,ELECT_SCOOTER,NAVIGO_SUB,IMAGINER_SUB,OTHER_SUB_PT,BIKE_SUB,NSM_SUB,WEIGHT_INDIV,GPS_RECORD
0,10_2978,78092,Bougival,Woman,41,NaN,4,In a couple with child(ren),2,1,...,1,2,0,False,False,False,False,False,1856.20616,True

In [7]:
trips_df.head(1)

,KEY,ID,Day_EMG,Date_EMG,Day_Type,ID_Trip_Days,Type_Trip_OD,Area_O,Area_D,Code_INSEE_O,...,Duration,Purpose_O,Purpose_D,Main_Mode,Mode_1,Mode_2,Mode_3,Mode_4,Mode_5,Weight_Day
0,42_0001-monday-44851-PDD,42_0001,monday,2022-10-17,Normal,No_Trip,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.171946